### ISSUE TITLE
TT ender 3 S1 Plus firmware build is still faulty (v23) just as v20 was.

### ISSUE THREAD

**Issue by mortensenal** [ThomasToka/Ender-3-pro-Marlin-Firmware#1]
I loaded the Pro firmware package you recently posted to my Ender 3 s1 Plus display then loaded 20231222-190624-E3S1Plus-ubl-v023-F4.bin. Just as before with the v 20 release, the print head homes correctly until I enter the tramming page.  Even before I place any values in the variables at the top of the page or even run a manual tram, If I hit the home again, the print head believes the center of the bed is the x limit. If I exit the tramming page and go to ready page and hit the X/Y home button, the print head moves to Y0 but then jams to X310 and Y150. I am sick and tired of the head jamming as the stepper motor drags it unforgivingly into the right X stop.  This has not changed since I noted it before on the guy's page that pitches your firmware builds on youtube (Zeltroix). I was pretty pissy after having the print head jam three times in three starts today. Cannot tram the machine and get it to rehome. You also have some firmware issue that is causing the hot end to go thermal overtemp as soon as the usb cable is plugged in.  

Dude I like your interface and the fact that you have so much config stuff available on the display, but It IS NOT FUNCTIONAL!

I know you spend a lot of hours on this stuff and qudos for that but, this firmware isn't beta worthy at the moment.

Adam M

**Comment by ThomasToka** [comment]
your request ist invalid. there are no problems on the plus.
also you are in the wrong section.
please join my discord. 
we will help you to do the basic calibration that needs to be done.
